### ISSUE TITLE
Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!

### ISSUE THREAD

**Issue by 600849155** [AeroXi/followBot#4]
运行程序提示：
 

Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!
     at Object.TransactionError (/repo/follow_mint_bot/node_modules/web3-core-helpers/lib/errors.js:87:21)
     at /repo/follow_mint_bot/node_modules/web3-core-method/lib/index.js:426:49
     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   receipt: undefined

**Comment by 600849155** [comment]
请问一下这个有没有什么方法解决
